### ISSUE TITLE
addMarker method not returning MapObject

### ISSUE THREAD

**Issue by DurankGts** [codenameone/codenameone-google-maps#10]
Hi, 

addMarket method It just return MapObject the first time but When use removeMapObject metthod and I use addMarker method it return null value.

```
                                if (moAgent != null) {
                                    mc.removeMapObject(moAgent);

                                }
                                moAgent = mc.addMarker(i, c, agentName, agentName, new ActionListener() {
                                    public void actionPerformed(ActionEvent evt) {
                                        Log.i(TAG, methodName + "()->agentName click:" + agentName);
                                    }
                                });
```

**Comment by shannah** [comment]
Can't reproduce.  Please provide full test case.

**Comment by DurankGts** [comment]
Could you tell how can I create this full test case?

**Comment by shannah** [comment]
Create a minimal demo app that exhibits the behaviour and post the main class of this app (i.e. the one with start(), stop(), etc... ) as a github gist.

I should be able to create a new project on my end, paste your class in, and reproduce the problem.

**Comment by DurankGts** [comment]
if I have two marker point added in my map, how can I update any of this marker with out delete the other marker point?

**Comment by DurankGts** [comment]
how can I update now this cn1 lib with this new fix that you applied?

**Comment by shannah** [comment]
It will be available shortly in the Codename One extensions (in codename one settings).  Just check there and it the button says "Update", then the update is there.

**Comment by shannah** [comment]
https://github.com/codenameone/codenameone-google-maps/blob/master/GoogleMapsTest/src/com/codename1/test/googlemaps/GoogleMapsTestApp.java#L108-L117
