### ISSUE TITLE
How can I add this cn1lib source code to my project

### ISSUE THREAD

**Issue by DurankGts** [codenameone/codenameone-google-maps#11]

**Comment by DurankGts** [comment]
I checked but there is not nothing update. When this fix it will available?

**Comment by shannah** [comment]
I have added the build to github
https://github.com/codenameone/codenameone-google-maps/blob/master/GoogleMaps.cn1lib

Not sure when it will be available in Codename one extensions.  Probably later today

**Comment by DurankGts** [comment]
thank you

**Comment by DurankGts** [comment]
I update you cn1lib compile and added to my problem but the problem it continue. the addMarker is not retuning value (null) when I remove first and I add the marker againg

**Comment by DurankGts** [comment]
Excuse me my english please...

**Comment by shannah** [comment]
You need to provide a test case then..  I won't look at this further until you have a test case.

**Comment by DurankGts** [comment]
ok, forge it this issue . Can you help me how can I Update a marker point without delete other markers added to the map?
