### ISSUE TITLE
Race condition issue on JS Port

### ISSUE THREAD

**Issue by blessingmobile** [codenameone/codenameone-google-maps#13]
Hi, the **com.codename1.googlemaps.MapContainer** has a race condition on JS Port web browser (Chrome & Firefox) & mobile device (Huawei Android 5.0). Note this issue does not occur on Android & iOS. It occurs on Simulator (sometimes) & HTML5 port (always).

I managed to isolate the cause of this issue. The issue occurs when I declare a **MapContainer** & immediately call its **zoom** or **setCameraPosition** or **addMarker** methods ie:
```
final MapContainer cnt = new MapContainer(HTML_API_KEY);
cnt.setCameraPosition(new Coord(-26.1486233, 28.67401229999996));//this breaks the code //because the Google map is not loaded yet
```

**Comment by shannah** [comment]
I have made some adjustments that seems to fix this issue.  You can either download the latest [here](https://github.com/codenameone/codenameone-google-maps/blob/master/GoogleMaps.cn1lib) or update in Codename One Settings (version number is 13 and should be available soon).

Ref https://github.com/codenameone/codenameone-google-maps/commit/8d59ca5afc5bf47e64d6e3e9a45aacd3d89d8718
and
https://github.com/codenameone/codenameone-google-maps/commit/d4f6560b9bb6bf04952535a27c028110d630c73d

**Comment by blessingmobile** [comment]
Hi Steve, just tested. Issue is fixed. Thanks!
