### ISSUE TITLE
I can't Write in my forked repository

### ISSUE THREAD

**Issue by DurankGts** [codenameone/codenameone-google-maps#15]
hi, I fork your googleMap repository to add some changes by it don' let me write in my forked repositoy. This the message of the git

https://Durank@github.com/DurankGts/codenameone-google-maps.git: not authorized

**Comment by DurankGts** [comment]
can some one helpme ?

**Comment by shannah** [comment]
This is a git related question, so this isn't the best forum to ask it.  A quick google search found [this](http://stackoverflow.com/questions/14259265/egit-not-authorized)
