### ISSUE TITLE
Marker event not working in simulator

### ISSUE THREAD

**Issue by rwanghk** [codenameone/codenameone-google-maps#21]
When using the JavaScript Google maps on simulator, the marker events is mostly (but not always) not called. Test code:

```
        Form hi = new Form();
        MapContainer mc = new MapContainer("_________key_here____________");

        hi.add(mc);
        mc.addMarker(null, new Coord(22, 110), "vbsean", "AVe", (evt) -> {
        	System.out.println("Bing");
        });
        hi.show();
```

**Comment by tmancini** [comment]
I experience this as well.  I've been told it could have something to do with the skin being used in the simulator, however The marker events and tap events on the map rarely seem to work for me in the simulator.

**Comment by shannah** [comment]
So far I haven't been able to reproduce this.  Could be OS specific.  What OS and Java versions are you running?

**Comment by tmancini** [comment]
Windows 10 with JRE 1.8.0_144

**Comment by tmancini** [comment]
I thought it might be worth mentioning that I'm using the 64-bit JRE
