### ISSUE TITLE
custom marker component

### ISSUE THREAD

**Issue by ramsestom** [codenameone/codenameone-google-maps#24]
I would like to use custom markers on my map (a marker that display some price information and has a dynamic background color). With MapComponent, wich used layers, it was possible to add any CN1 component as a marker. With this lib, only native markers are directly supported (that can only be an image) and no overlay layer has been implemented. So I guess it is up to the user to do this. 
I am wondering how this would render in term of performances though. If I have let's say 50 markers defined as CN1 components that are rendered on top of the native map, would this be an issue?
Also, how can I move the overlay markers at the same time as the map? Should I just register a MapListener and rerender my markers at each change?

**Comment by codenameone** [comment]
I think it's best to ask this here: https://www.codenameone.com/blog/map-layout-update.html
The issue tracker is probably not a good place for questions as few people will see them. You should refer questions to stackoverflow http://stackoverflow.com/tags/codenameone
or the discussion forum https://www.codenameone.com/discussion-forum.html

Notice the map layout does all of that automatically. I haven't done stress testing on a huge number of markers though I would wager you should be safe in the 100+ marker count.
