### ISSUE TITLE
expected final app size increase when using this lib?

### ISSUE THREAD

**Issue by ramsestom** [codenameone/codenameone-google-maps#25]
The cn1 lib file is quite small (42ko) but I know the iOS SDK for google map is quite big (dozen of Mb) and, from what I found in the net, using this SDK in a native iOS app usually add a few Mb (~4-5Mb) to this app size. So I am wondering how the .cn1 lib file could be so small. Does this mean that it do not include the iOS Google map SDK? (for android it doesn't have as it is provided by google play service that is part of the android SDK). In which case how can the compilation server include necessary parts of this SDK in the final app? 
And finally, how much would an iOS app grow when using this library (compared to the same app without native google maps)?

**Comment by codenameone** [comment]
The issue tracker is probably not a good place for questions as few people will see them. You should refer questions to stackoverflow http://stackoverflow.com/tags/codenameone
or the discussion forum https://www.codenameone.com/discussion-forum.html

Those are included using gradle/cocoapods respectively so the build server process fetches that data seamlessly. I can't really tell how much the final app grows in size as it depends on too many factors and is hard to measure (code stripping/obfuscation makes that difficult).
