### ISSUE TITLE
Error Compiling library

### ISSUE THREAD

**Issue by DurankGts** [codenameone/codenameone-google-maps#26]
Hi, I made a fork of this library but when I compile this error it occur.

Please help to solve this issue:

warning: [options] bootstrap class path not set in conjunction with -source 1.6
1 warning
Init env executing with cn1env = ${cn1env} for ../../CodenameOne/GUIBuilder/src
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Compile is forcing compliance to the supported API's/features for maximum device compatibility. This allows smaller
        code size and wider device support
An exception has occurred in the compiler (1.8.0_121). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.lang.invoke.MethodType not found
F:\data_kdp\programs\CodenameOne\ws_codenameone\codenameone-google-maps\GoogleMaps\build.xml:28: Compile failed; see the compiler error output for details.
BUILD FAILED (total time: 41 seconds)

In line 28 there is

    <target name="-pre-compile">
        <echo>Compile is forcing compliance to the supported API's/features for maximum device compatibility. This allows smaller
        code size and wider device support</echo>
        <mkdir dir="build/tmp"/>
        <javac destdir="build/tmp"
            source="1.8"
            target="1.8"
            bootclasspath="lib/CLDC11.jar"
            ****classpath="${javac.classpath}:${build.classes.dir}">****
            <src path="${src.dir}"/>
        </javac>        
    </target>

**Comment by shannah** [comment]
Try a clean build.  You might have some lingering internal classes from a previous compile.
Alternatively try a different JDK.

**Comment by DurankGts** [comment]
I try clean and built but the problem it continue I download jdk 1.8.171 but the problem it continue.

**Comment by shannah** [comment]
I don't know then.  I'm able to build fine.  I've used many different 1.8 JDK versions.  Have you made any changes in your fork, or is it identical to the master?

**Comment by DurankGts** [comment]
it's identical to the master

**Comment by DurankGts** [comment]
![image](https://user-images.githubusercontent.com/16245755/39831420-5ff88412-5392-11e8-8bd1-bb81ba22250f.png)


this when I clone the project. I resolve with the correct reference but the problem it continue

![image](https://user-images.githubusercontent.com/16245755/39831460-8e2630be-5392-11e8-8535-e78fd8d886ae.png)

**Comment by shannah** [comment]
Did you correct the project dependencies (e.g. CodenameOne in the compile deps and JavaSE in run deps)?

I just did a fresh clone, then `cn1 install-jars` (i.e. fix dependencies using cli tool), then `ant jar` and it built fine.  I'm using jdk 1.8.0u151 on OS X 10.13.4.

**Comment by DurankGts** [comment]
this other error 

ant -q -f F:\\data_kdp\\programs\\CodenameOne\\ws_codenameone\\codenameone-google-maps\\GoogleMaps -Dnb.internal.action.name=rebuild clean jar
Compile is forcing compliance to the supported API's/features for maximum device compatibility. This allows smaller
        code size and wider device support
Note: F:\data_kdp\programs\CodenameOne\ws_codenameone\codenameone-google-maps\GoogleMaps\src\com\codename1\googlemaps\MapContainer.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: F:\data_kdp\programs\CodenameOne\ws_codenameone\codenameone-google-maps\GoogleMaps\src\com\codename1\googlemaps\MapContainer.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: F:\data_kdp\programs\CodenameOne\ws_codenameone\codenameone-google-maps\GoogleMaps\src\com\codename1\googlemaps\MapContainer.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: F:\data_kdp\programs\CodenameOne\ws_codenameone\codenameone-google-maps\GoogleMaps\src\com\codename1\googlemaps\MapContainer.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Zipping ios native code
Zipping rim native code
Zipping Android native code
Zipping JavaSE native code
Zipping win native code
Zipping me native code
Zipping Javascript native code
Attempt to copy F:\data_kdp\programs\CodenameOne\ws_codenameone\codenameone-google-maps\GoogleMaps\dist\GoogleMaps.cn1lib to C:\Users\shannah\cn1_files\tests\AppleMapsTest1213\lib\GoogleMaps.cn1lib using NIO Channels failed due to 'failed to create the parent directory for C:\Users\shannah\cn1_files\tests\AppleMapsTest1213\lib\GoogleMaps.cn1lib'.  Falling back to streams.
F:\data_kdp\programs\CodenameOne\ws_codenameone\codenameone-google-maps\GoogleMaps\build.xml:79: Failed to copy F:\data_kdp\programs\CodenameOne\ws_codenameone\codenameone-google-maps\GoogleMaps\dist\GoogleMaps.cn1lib to C:\Users\shannah\cn1_files\tests\AppleMapsTest1213\lib\GoogleMaps.cn1lib due to java.io.FileNotFoundException C:\Users\shannah\cn1_files\tests\AppleMapsTest1213\lib\GoogleMaps.cn1lib (The system cannot find the path specified)


you let your local directory in the build.xml

    <target name="jar" depends="compile,Stubs">
        <mkdir dir="build/lib" />
        <mkdir dir="build/stubs"/>
        <zip basedir="${build.classes.dir}" compress="false" destfile="build/lib/main.zip" />
        <zip basedir="build/stubs" compress="false" destfile="build/lib/stubs.zip" />
        <copy file="manifest.properties" todir="build/lib" />
        <copy file="codenameone_library_appended.properties" todir="build/lib" />
        <copy file="codenameone_library_required.properties" todir="build/lib" />
        <copy file="codenameone_library.properties" todir="build/lib" />
        <antcall target="buildNativeIOS" />        
        <antcall target="buildNativeRIM" />        
        <antcall target="buildNativeAND" />        
        <antcall target="buildNativeSE" />        
        <antcall target="buildNativeWIN" />        
        <antcall target="buildNativeME" />  
        <antcall target="buildNativeJavascript" />     
        <mkdir dir="dist" />
        <zip basedir="build/lib" compress="true" destfile="dist/${application.title}.cn1lib" />
        <copy file="dist/GoogleMaps.cn1lib" todir="../GoogleMapsTest/lib/" />
        <ant dir="../GoogleMapsTest" target="refresh-libs"/>
        <copy file="dist/GoogleMaps.cn1lib" **todir="/Users/shannah/cn1_files/tests/AppleMapsTest1213/lib/" />
        <ant dir="/Users/shannah/cn1_files/tests/AppleMapsTest1213" target="refresh-libs"** usenativebasedir="true"/>
    </target>
