### ISSUE TITLE
Functionality requested: integrate the address search functionality via native.

### ISSUE THREAD

**Issue by romancanoniero** [codenameone/codenameone-google-maps#28]
HI, as i seen the samples that i found to search an address in google maps and get the location's data (normalized address, lat, lon, etc) access to the service via connectionrequest and that means the quota is limited and sensible slow, meanwhile if we access via the native functionality (android/ios native functionality) the service is unlimited and free and the most important thing is that is faster.

can you help me telling me if it already was developed or how to do it keeping in mind that im not an expert in ios and java?

thanks

**Comment by codenameone** [comment]
Is this a question? I'm unclear on what is being asked. You can access the device navigation API via the `Display` class.

**Comment by romancanoniero** [comment]
no... its a functionality that i request.

im asking to access to the geocode functionality of maps via the native api and not via connectionrequest

**Comment by romancanoniero** [comment]
i need to search an address and get the lattitude and longitude (and the another fields) from a native call (also with the suggested address when are more than 1)

**Comment by shannah** [comment]
Can you provide a link to documentation that talks about the service being free and unlimited when using native APIs?  This doesn't really make sense to me that this would be the case.  Native APIs ultimately use the REST APIs under the hood, so I don't get how/why they would be unlimited.

In any case, this sounds like it could be its own cn1lib.  Any reason why you think this should be part of the google maps cn1lib?  Does it depend on maps in any way?  If you can post links to the actual APIs you want to wrap, that will help.

**Comment by romancanoniero** [comment]
i was thinking to use the same method that the google maps app use to search addresses because nobody pays for that and there is not limit of querys,

my objetive is to use the same method that is used to search in google maps when you search some address, that is faster that the avalaible method (rest )

**Comment by codenameone** [comment]
@romancanoniero To use the native Google Maps API you need an API key with a quota and billing. In fact Google pushed up the price on that significantly recently.

**Comment by romancanoniero** [comment]
thanks
