### ISSUE TITLE
functionality requested : native search places

### ISSUE THREAD

**Issue by romancanoniero** [codenameone/codenameone-google-maps#29]
HI, days a go i was asking to implement the places search in native way.

as i already implement the incremental search of addreses usign connectionrequest and the performance is not good and i check that in a native app is faster than my method, i want to ask you if its possible to implement it in cn1.

in android exists a functionality that makes really fast the task but i dont know how to implement it in CN1, the link is https://developers.google.com/places/android-sdk/autocomplete?hl=es

thanks

**Comment by codenameone** [comment]
Native won't make it faster https://groups.google.com/d/msg/codenameone-discussions/BNOZb1bEUKM/Gc7HF1bOBAAJ
