### ISSUE TITLE
The Google Maps JavaScript API does not support this browser

### ISSUE THREAD

**Issue by kutoman** [codenameone/codenameone-google-maps#30]
My `MapContainer` gets not displayed in the simulator and I'm getting the mentioned error (`"[JS Console] Found exception Error:..".`). I've checked the native browser (it is Safari) and the API Key I'm passing to the `MapContainer` instance, which are actually correct / compatible.

**Comment by shannah** [comment]
Note:  Works in jdk 1.8u162, but not in 1.8u144.

Problem is that Google maps now requires requestAnimationFrame, which apparently is available sometime after u144.

Will add this as a polyfill.
