### ISSUE TITLE
addMarker always returns 0

### ISSUE THREAD

**Issue by kutoman** [codenameone/codenameone-google-maps#31]
what is the purpose of the key returned by the JS function? I suppose it should return the newely incremeneted key? This is not happening since the incrementing does not happen sequentially.

**Comment by shannah** [comment]
addMarker returns an object that you can later use to remove the marker from the map.  It is an object, not a number.  I’m not sure where you are getting the zero from.

**Comment by shannah** [comment]
Is this in the simulator in the Javascript port?  Where exactly did you add this snippet?

~~~~
window.jconsole.log("KEY" + key);
return key;
~~~~

**Comment by shannah** [comment]
Where exactly did you add this?  Can you post a gist of our entire version of that file?

**Comment by kutoman** [comment]
it is between those lines which are already existing in that function:

                    //console.log("Returning key "+key);
                    return key;

here is the gist:
https://gist.github.com/kutoman/f2c30bc60be508edac64a743770bf61b

**Comment by kutoman** [comment]
the returned keys only get unique if I run my code in debug mode (thus it's slow enough so that the callback in which the key is incremented gets called sequentially before `return key`)
            
          addMarker : function(imageIcon, lat, lon, text, longText, imageWidth, imageHeight, anchorU, anchorV){
                    var key = 0;
                    
                    this.ready(function() { //by callback I mean this section
