### ISSUE TITLE
Map goes black on Android if a TextField is edited.

### ISSUE THREAD

**Issue by shannah** [codenameone/codenameone-google-maps#5]

**Comment by codenameone** [comment]
This also happens when the app is first installed https://groups.google.com/d/msg/codenameone-discussions/O0iBhFyDesQ/8GoU7pEJEAAJ

**Comment by shannah** [comment]
I have it working locally now.. but I had to disable the "paintOnBuffer" flag.  The problem is that you can't paint a google MapView that way.

https://github.com/codenameone/CodenameOne/blob/master/Ports/Android/src/com/codename1/impl/android/AndroidAsyncView.java#L202

@codenameone Do you remember why we have that "paintOnBuffer" flag?  Is there a scenario I should test?
