### ISSUE TITLE
unable to build on uwp

### ISSUE THREAD

**Issue by howudodat** [codenameone/codenameone-google-maps#9]
Steps to reproduce:
Create new project.  Add cn1lib.  Add MapContainer.  Build for UWP

The following error appears when the build fails
`[exec] Done Building Project "C:\Users\CODENA~1\AppData\Local\Temp\build7766042901287633407xxx\TestProject\UWPProject\UWPApp\UWPApp.csproj" (default targets) -- FAILED.
     [exec] 
     [exec] Build FAILED.
     [exec] 
     [exec] "C:\Users\CODENA~1\AppData\Local\Temp\build7766042901287633407xxx\TestProject\UWPProject\UWPApp\UWPApp.csproj" (default target) (1) ->
     [exec] (XamlPreCompile target) -> 
     [exec]   src\com\codename1\googlemaps\InternalNativeMapsImpl.cs(8,55): error CS1001: Identifier expected [C:\Users\CODENA~1\AppData\Local\Temp\build7766042901287633407xxx\TestProject\UWPProject\UWPApp\UWPApp.csproj]
`

**Comment by shannah** [comment]
I have fixed the build error.  Will be available in Codename One extensions shortly.  For now, UWP will still fall back to using the CN1 MapComponent.  Eventually we'll be implementing BingMaps on that platform.
